### ISSUE TITLE
generator name is too long

### ISSUE THREAD

**Issue by ghost** [tpickett/express-microservice-generator#1]
`generator-express-microservice-generator` is just not acceptable. I can't even count the number of characters I need on just one hand, or even two hands, or even two hands and two feet in order to type all that! How can you possible expect me to use this. Want me to grow extra appendages? Want me to become some hideously deformed creature for your amusement? Is that what you want? Well don't hold your breath because I'll NEVER succumb to your extra limb demands. The way I see it your only option is to fix this issue. Or resign immediately. Or honorably eviscerate yourself. Or fight me to the death. See? You're running out of options here.

![giphy 2](https://cloud.githubusercontent.com/assets/14224088/15551287/e95d4d32-227a-11e6-8aa8-bdf38de0bb9b.gif)

**Comment by ghost** [comment]
Also I'm getting 404s when I try to run `npm install -g generator-express-microservice-generator`

![404](https://cloud.githubusercontent.com/assets/14224088/15551357/2fd80cfc-227b-11e6-99f4-f8b60c0db5e5.png)

**Comment by tpickett** [comment]
uh i think you fixed this in merge request https://github.com/tpickett/express-microservice-generator/pull/3. 

I choose evisceration... but i can't do it so my trusty steed will oblige you:
![image](https://cloud.githubusercontent.com/assets/2249555/15554379/7effe102-2289-11e6-869d-cabaeecfea3c.png)
